// <auto-generated />
namespace CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Version30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version30));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081849483_Version 3.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
